"use strict";
window.HD = window.HD || {};
HD.CONFIG = {
  // ---------------------------------------------------------------------------
  // Race and match rules
  // ---------------------------------------------------------------------------

  horses: [
    { id: "hoof-hearted", name: "Hoof Hearted", color: 0xef476f, odds: 3, ability: 1.05, coat: 0x6b3824 },
    { id: "mayo-neighs", name: "Mayo Neighs", color: 0x3a86ff, odds: 5, ability: 1.01, coat: 0x3e2921 },
    { id: "sir-gallops", name: "Sir Gallops", color: 0xffbe0b, odds: 7, ability: 0.98, coat: 0xa45a31 },
    { id: "pony-soprano", name: "Pony Soprano", color: 0x9b5de5, odds: 10, ability: 0.95, coat: 0xddd1b9 },
    { id: "neigh-sayer", name: "Neigh Sayer", color: 0x22b573, odds: 13, ability: 0.92, coat: 0x7a4930 },
    { id: "usain-colt", name: "Usain Colt", color: 0xff7b22, odds: 4, ability: 1.03, coat: 0x2e2723 },
    { id: "mane-event", name: "Mane Event", color: 0x42d4d4, odds: 8, ability: 0.97, coat: 0x8b4f2f },
    { id: "stable-genius", name: "Stable Genius", color: 0xf06cad, odds: 6, ability: 1, coat: 0xc4a27c },
    { id: "gallop-poll", name: "Gallop Poll", color: 0xe84a5f, odds: 11, ability: 0.94, coat: 0x4b3027 },
    { id: "bit-coin", name: "Bit Coin", color: 0x5c7cfa, odds: 5, ability: 1.02, coat: 0x9a603f },
    { id: "hay-there", name: "Hay There", color: 0xf4a261, odds: 12, ability: 0.93, coat: 0xd5c4a1 },
    { id: "night-mare", name: "Night Mare", color: 0x845ec2, odds: 4, ability: 1.04, coat: 0x211d1d },
    { id: "track-snack", name: "Track Snack", color: 0x2a9d8f, odds: 9, ability: 0.96, coat: 0x74482f },
    { id: "rein-check", name: "Rein Check", color: 0xe9c46a, odds: 7, ability: 0.99, coat: 0xb78252 },
    {
      id: "fast-flurrious",
      name: "Fast & Flurrious",
      color: 0x00b4d8,
      odds: 3,
      ability: 1.06,
      coat: 0xe2d3bb,
    },
    { id: "clip-clop", name: "Clip Clop", color: 0xf28482, odds: 14, ability: 0.91, coat: 0x5b3829 },
    { id: "saddle-up", name: "Saddle Up", color: 0x84a59d, odds: 8, ability: 0.98, coat: 0x99633f },
    { id: "foal-play", name: "Foal Play", color: 0xf6bd60, odds: 10, ability: 0.95, coat: 0xc6b08c },
    { id: "buck-stops", name: "Buck Stops Here", color: 0x577590, odds: 6, ability: 1.01, coat: 0x432b24 },
    { id: "pasture-prime", name: "Pasture Prime", color: 0x90be6d, odds: 9, ability: 0.97, coat: 0x815235 },
    { id: "canter-banter", name: "Canter Banter", color: 0xf94144, odds: 12, ability: 0.93, coat: 0x2d2725 },
    { id: "photo-finish", name: "Photo Finish", color: 0x277da1, odds: 5, ability: 1.03, coat: 0xb36b3d },
    {
      id: "derby-mcderby",
      name: "Derby McDerbyface",
      color: 0xf8961e,
      odds: 13,
      ability: 0.92,
      coat: 0xd8c5a4,
    },
    { id: "long-shot", name: "The Long Shot", color: 0x6a4c93, odds: 15, ability: 0.9, coat: 0x70452f },
  ],
  playerColors: [0xef476f, 0x3a86ff, 0xffbe0b, 0x9b5de5, 0x22b573, 0xff7b22, 0x42d4d4, 0xf06cad],
  items: {
    hotdog: {
      name: "Ballpark Hotdog",
      icon: "🌭",
      price: 8,
      speed: 36,
      lift: 8,
      gravity: 19,
      ragdollDuration: 1.8,
      description: "Startles a horse into rearing and briefly stops its stride.",
    },
    soda: {
      name: "Mega Soda",
      icon: "🥤",
      price: 14,
      speed: 42,
      lift: 7,
      gravity: 21,
      slowDuration: 3.6,
      description: "Travels quickly and gives a horse a sticky surprise.",
    },
    horseshoe: {
      name: "Foam Horseshoe",
      icon: "🧲",
      price: 24,
      speed: 31,
      lift: 10,
      gravity: 16,
      slowDuration: 5,
      ragdollDuration: 2.4,
      description: "A heavy hit that startles and slows the target.",
    },
    carrot: {
      name: "Turbo Carrot",
      icon: "🥕",
      price: 20,
      speed: 38,
      lift: 8,
      gravity: 18,
      boostDuration: 5,
      resistanceDuration: 8,
      description: "Boosts a horse and grants temporary interference resistance.",
    },
    hurdle: {
      name: "Foam Hurdle",
      icon: "🚧",
      price: 18,
      speed: 30,
      lift: 11,
      gravity: 17,
      slowDuration: 1.2,
      forceLaneChange: true,
      trap: true,
      heldScale: 0.58,
      description: "Stays on the track and forces the first horse it catches to change lanes.",
    },
    pillow: {
      name: "Throw Pillow",
      icon: "🛏️",
      price: 16,
      speed: 27,
      lift: 12,
      gravity: 13,
      ragdollDuration: 1.4,
      vendorOnly: true,
      description: "Concourse exclusive. Light, floaty, and startling.",
    },
    chair: {
      name: "Folding Chair",
      icon: "🪑",
      price: 42,
      speed: 25,
      lift: 9,
      gravity: 20,
      slowDuration: 4,
      ragdollDuration: 3.5,
      vendorOnly: true,
      description: "Concourse exclusive. Heavy, slow, and a powerful startle.",
    },
    pretzel: {
      name: "Giant Pretzel",
      icon: "🥨",
      price: 10,
      speed: 35,
      lift: 8,
      gravity: 18,
      slowDuration: 1.6,
      ragdollDuration: 1.1,
      heldScale: 0.78,
      description: "A bendy snack with a balanced arc and a short startle.",
    },
    bananaPeel: {
      name: "Banana Peel",
      icon: "\ud83c\udf4c",
      price: 18,
      speed: 30,
      lift: 10,
      gravity: 15,
      slowDuration: 2.4,
      weaveDuration: 4.5,
      heldScale: 0.82,
      description: "Forces a horse to lose footing and drift toward another lane.",
    },
    airHorn: {
      name: "Air Horn",
      icon: "\ud83d\udce3",
      price: 28,
      speed: 39,
      lift: 7,
      gravity: 19,
      panicDuration: 3.2,
      heldScale: 0.78,
      vendorOnly: true,
      description: "Concourse exclusive. Causes a panicked swerve and uneven pace.",
    },
  },
  sabotageOptions: {
    looseShoe: {
      name: "Sticky Starting Gate",
      price: 70,
      startDelay: 1.5,
      description: "Makes the target leave the gate 1.5 seconds late.",
    },
    badFeed: {
      name: "Missing Saddle Call",
      price: 105,
      startDelay: 2.8,
      description: "Delays the target at the start by 2.8 seconds.",
    },
    gateTampering: {
      name: "Weighted Saddle",
      price: 145,
      penalty: 0.15,
      description: "Reduces performance by 15% for the entire race.",
    },
    hotStart: {
      name: "Hot Start Tip",
      price: 90,
      boostDuration: 15,
      description: "Secretly boosts the target for the first 15 seconds.",
    },
  },
  sabotageFailureChance: 0.33,
  roundBonuses: [100, 150, 250],
  racesPerRound: 2,
  totalRaces: 6,
  raceLaps: 3,
  raceHorseCount: 8,
  horseFieldRaces: 2,
  grandstandBaseHeight: 2.75,

  stairs: {
    startX: 78.5,
    startZ: 48,
    endX: 103.25,
    endZ: 69.75,
    width: 7.2,
    bottomHeight: 1.65,
    topHeight: 13.5,
  },
  liveBettingDuration: 15,
  preparationDuration: 30,
  roundBreakDuration: 60,
  phoneDeliveryDuration: 12,
  vendorDiscount: 0.33,
  onlineBetFeeRate: 0.08,
  throwVelocityMultiplier: 1,
  walkSpeed: 11.5,
  seat: new THREE.Vector3(8, 12.73, 60.85),
  playerSeatRoot: new THREE.Vector3(8, 9.45, 60.85),
  playerSeatYaw: 0,
  characterEyeOffset: 3.28,
  eyeHeight: 4.8,
};

HD.createInventory = () =>
  Object.fromEntries(Object.keys(HD.CONFIG.items).map((itemId) => [itemId, 0]));

HD.state = {
  money: 100,
  inventory: HD.createInventory(),
  selectedItem: "hotdog",
  round: 1,
  race: 1,
  selected: 0,
  bets: [],
  ledger: [],
  phase: "betting",
  timer: 30,
  raceTime: 0,
  horses: [],
  activeHorseIds: [],
  horseFieldRacesRemaining: 0,
  horseBag: HD.CONFIG.horses.map((horse) => horse.id),
  projectiles: [],
  finishOrder: [],
  elapsed: 0,
  lastOdds: 0,
  paused: true,
  mode: "look",
  yaw: 0,
  pitch: -0.18,
  throwPower: 0,
  charging: false,
  deliveries: [],
  standing: false,
  playerPosition: new THREE.Vector3(8, 12.73, 60.85),
  movement: { forward: false, backward: false, left: false, right: false },
  vendorOpen: false,
  counterOpen: false,
  sabotagePlans: [],
  raceAnnouncement: "",
  matchStarted: false,
};
HD.world = {
  remotePlayers: new Map(),
};
HD.util = {
  material(color, extra = {}) {
    return new THREE.MeshStandardMaterial({ color, roughness: 0.78, metalness: 0.025, ...extra });
  },
  mesh(geometry, color, parent, position = [0, 0, 0], extra = {}) {
    const object = new THREE.Mesh(geometry, HD.util.material(color, extra));
    object.position.set(...position);
    object.castShadow = object.receiveShadow = true;
    parent.add(object);
    return object;
  },
  box(size, color, parent, position) {
    return HD.util.mesh(new THREE.BoxGeometry(...size), color, parent, position);
  },
  sphere(radius, color, parent, position) {
    return HD.util.mesh(new THREE.SphereGeometry(radius, 14, 10), color, parent, position);
  },
  cylinder(top, bottom, height, color, parent, position, segments = 12) {
    return HD.util.mesh(
      new THREE.CylinderGeometry(top, bottom, height, segments),
      color,
      parent,
      position,
    );
  },
};
