"use strict";
window.HD = window.HD || {};

function makeHorseProfile(profile) {
  const rating =
    profile.speed * 0.45 +
    profile.stamina * 0.25 +
    profile.acceleration * 0.2 +
    profile.resistance * 0.1;

  return {
    ...profile,
    ability: 0.84 + rating * 0.0024,
    maxSpeed: profile.maxSpeed ?? profile.speed,
    cornering: profile.cornering ?? Math.round(
      profile.acceleration * 0.55 + profile.resistance * 0.45,
    ),
    recovery: profile.recovery ?? profile.resistance,
    startingPerformance: profile.startingPerformance ?? profile.acceleration,
    finalStretch: profile.finalStretch ?? profile.stamina,
    consistency: profile.consistency ?? Math.round(
      profile.stamina * 0.6 + profile.resistance * 0.4,
    ),
  };
}

HD.CONFIG = {
  // The retired broadcast experiment is deliberately kept in the source behind
  // these switches. Turning both flags back on restores its construction and
  // speech path without having to recover deleted code.
  features: {
    commentator: false,
    commentatorBooth: false,
  },

  // ---------------------------------------------------------------------------
  // Race and match rules
  // ---------------------------------------------------------------------------
 
  horses: [
    makeHorseProfile({
      id: "midnight-sovereign",
      name: "Monarch",
      color: 0xef476f,
      coat: 0x241c1a,
      odds: 3,
      speed: 92,
      stamina: 86,
      acceleration: 88,
      resistance: 72,
      style: "Front Runner",
    }),
    makeHorseProfile({
      id: "silver-comet",
      name: "Comet",
      color: 0x3a86ff,
      coat: 0xb8b9b4,
      odds: 4,
      speed: 90,
      stamina: 79,
      acceleration: 94,
      resistance: 66,
      style: "Closer",
    }),
    makeHorseProfile({
      id: "autumn-valor",
      name: "Valor",
      color: 0xffbe0b,
      coat: 0x9b4e29,
      odds: 6,
      speed: 84,
      stamina: 88,
      acceleration: 78,
      resistance: 82,
      style: "Balanced",
    }),
    makeHorseProfile({
      id: "northern-tempest",
      name: "Tempest",
      color: 0x9b5de5,
      coat: 0x4c3b35,
      odds: 5,
      speed: 88,
      stamina: 82,
      acceleration: 86,
      resistance: 73,
      style: "Stalker",
    }),
    makeHorseProfile({
      id: "crimson-banner",
      name: "Crimson",
      color: 0x22b573,
      coat: 0x6f3926,
      odds: 8,
      speed: 81,
      stamina: 84,
      acceleration: 80,
      resistance: 79,
      style: "Balanced",
    }),
    makeHorseProfile({
      id: "golden-promise",
      name: "Promise",
      color: 0xff7b22,
      coat: 0xc18a4c,
      odds: 7,
      speed: 85,
      stamina: 77,
      acceleration: 89,
      resistance: 68,
      style: "Front Runner",
    }),
    makeHorseProfile({
      id: "blue-meridian",
      name: "Meridian",
      color: 0x42d4d4,
      coat: 0x3f302b,
      odds: 9,
      speed: 79,
      stamina: 90,
      acceleration: 72,
      resistance: 84,
      style: "Closer",
    }),
    makeHorseProfile({
      id: "royal-ember",
      name: "Ember",
      color: 0xf06cad,
      coat: 0x7d4128,
      odds: 6,
      speed: 86,
      stamina: 83,
      acceleration: 82,
      resistance: 75,
      style: "Stalker",
    }),
    makeHorseProfile({
      id: "willow-creek",
      name: "Willow",
      color: 0xe84a5f,
      coat: 0xb18b64,
      odds: 11,
      speed: 76,
      stamina: 91,
      acceleration: 70,
      resistance: 88,
      style: "Closer",
    }),
    makeHorseProfile({
      id: "iron-resolve",
      name: "Titan",
      color: 0x5c7cfa,
      coat: 0x34302d,
      odds: 7,
      speed: 82,
      stamina: 87,
      acceleration: 76,
      resistance: 94,
      style: "Balanced",
    }),
    makeHorseProfile({
      id: "velvet-thunder",
      name: "Thunder",
      color: 0xf4a261,
      coat: 0x221d1d,
      odds: 5,
      speed: 89,
      stamina: 80,
      acceleration: 91,
      resistance: 69,
      style: "Front Runner",
    }),
    makeHorseProfile({
      id: "coastal-wind",
      name: "Zephyr",
      color: 0x845ec2,
      coat: 0xd0c4ae,
      odds: 10,
      speed: 80,
      stamina: 81,
      acceleration: 83,
      resistance: 71,
      style: "Stalker",
    }),
    makeHorseProfile({
      id: "scarlet-horizon",
      name: "Horizon",
      color: 0x2a9d8f,
      coat: 0xa96136,
      odds: 12,
      speed: 77,
      stamina: 79,
      acceleration: 81,
      resistance: 74,
      style: "Front Runner",
    }),
    makeHorseProfile({
      id: "noble-pursuit",
      name: "Noble",
      color: 0xe9c46a,
      coat: 0x5c382c,
      odds: 8,
      speed: 83,
      stamina: 85,
      acceleration: 77,
      resistance: 81,
      style: "Balanced",
    }),
    makeHorseProfile({
      id: "dancing-shadow",
      name: "Shadow",
      color: 0x00b4d8,
      coat: 0x2c2523,
      odds: 9,
      speed: 82,
      stamina: 75,
      acceleration: 92,
      resistance: 64,
      style: "Closer",
    }),
    makeHorseProfile({
      id: "western-legend",
      name: "Legend",
      color: 0xf28482,
      coat: 0x8c512f,
      odds: 10,
      speed: 78,
      stamina: 86,
      acceleration: 74,
      resistance: 87,
      style: "Stalker",
    }),
    makeHorseProfile({
      id: "emerald-bay",
      name: "Emerald",
      color: 0x84a59d,
      coat: 0xc0aa87,
      odds: 13,
      speed: 74,
      stamina: 89,
      acceleration: 69,
      resistance: 90,
      style: "Closer",
    }),
    makeHorseProfile({
      id: "storm-lantern",
      name: "Lantern",
      color: 0xf6bd60,
      coat: 0x514039,
      odds: 8,
      speed: 84,
      stamina: 78,
      acceleration: 87,
      resistance: 70,
      style: "Front Runner",
    }),
    makeHorseProfile({
      id: "quiet-majesty",
      name: "Majesty",
      color: 0x577590,
      coat: 0xd7d0c4,
      odds: 11,
      speed: 77,
      stamina: 92,
      acceleration: 68,
      resistance: 92,
      style: "Closer",
    }),
    makeHorseProfile({
      id: "copper-ridge",
      name: "Copper",
      color: 0x90be6d,
      coat: 0xa75f32,
      odds: 7,
      speed: 85,
      stamina: 82,
      acceleration: 79,
      resistance: 83,
      style: "Balanced",
    }),
    makeHorseProfile({
      id: "moonlit-harbor",
      name: "Harbor",
      color: 0xf94144,
      coat: 0x302927,
      odds: 12,
      speed: 76,
      stamina: 85,
      acceleration: 75,
      resistance: 86,
      style: "Stalker",
    }),
    makeHorseProfile({
      id: "grand-alliance",
      name: "Alliance",
      color: 0x277da1,
      coat: 0x74452f,
      odds: 6,
      speed: 87,
      stamina: 84,
      acceleration: 81,
      resistance: 78,
      style: "Balanced",
    }),
    makeHorseProfile({
      id: "summer-anthem",
      name: "Anthem",
      color: 0xf8961e,
      coat: 0xccaa76,
      odds: 9,
      speed: 81,
      stamina: 80,
      acceleration: 85,
      resistance: 67,
      style: "Front Runner",
    }),
    makeHorseProfile({
      id: "blackwater-belle",
      name: "Belle",
      color: 0x6a4c93,
      coat: 0x1e1b1b,
      odds: 4,
      speed: 91,
      stamina: 85,
      acceleration: 87,
      resistance: 80,
      style: "Stalker",
    }),
    makeHorseProfile({
      id: "highland-echo",
      name: "Echo",
      color: 0x43aa8b,
      coat: 0x8b725e,
      odds: 10,
      speed: 79,
      stamina: 83,
      acceleration: 80,
      resistance: 76,
      style: "Closer",
    }),
    makeHorseProfile({
      id: "riverstone",
      name: "Riverstone",
      color: 0xf3722c,
      coat: 0x6a4737,
      odds: 14,
      speed: 72,
      stamina: 88,
      acceleration: 67,
      resistance: 91,
      style: "Closer",
    }),
    makeHorseProfile({
      id: "bold-venture",
      name: "Venture",
      color: 0x4d908e,
      coat: 0x9a5c36,
      odds: 8,
      speed: 83,
      stamina: 79,
      acceleration: 88,
      resistance: 65,
      style: "Front Runner",
    }),
    makeHorseProfile({
      id: "winter-rose",
      name: "Rose",
      color: 0xf9844a,
      coat: 0xe0d9ca,
      odds: 11,
      speed: 78,
      stamina: 84,
      acceleration: 73,
      resistance: 89,
      style: "Balanced",
    }),
    makeHorseProfile({
      id: "sunset-courier",
      name: "Courier",
      color: 0x9b5de5,
      coat: 0xb76f3d,
      odds: 9,
      speed: 82,
      stamina: 76,
      acceleration: 90,
      resistance: 62,
      style: "Front Runner",
    }),
    makeHorseProfile({
      id: "cedar-run",
      name: "Cedar",
      color: 0x2d6a4f,
      coat: 0x65402d,
      odds: 15,
      speed: 71,
      stamina: 82,
      acceleration: 71,
      resistance: 85,
      style: "Stalker",
    }),
  ],
  playerColors: [0xef476f, 0x3a86ff, 0xffbe0b, 0x9b5de5, 0x22b573, 0xff7b22, 0x42d4d4, 0xf06cad],
  items: {
    hotdog: {
      name: "Ballpark Hotdog",
      icon: "🌭",
      price: 8,
      speed: 36,
      lift: 8,
      gravity: 19,
      ragdollDuration: 1.8,
      description: "Startles a horse into rearing and briefly stops its stride.",
    },
    soda: {
      name: "Mega Soda",
      icon: "🥤",
      price: 14,
      speed: 42,
      lift: 7,
      gravity: 21,
      slowDuration: 3.6,
      description: "Travels quickly and gives a horse a sticky surprise.",
    },
    horseshoe: {
      name: "Foam Horseshoe",
      icon: "🧲",
      price: 24,
      speed: 31,
      lift: 10,
      gravity: 16,
      slowDuration: 5,
      ragdollDuration: 2.4,
      description: "A heavy hit that startles and slows the target.",
    },
    carrot: {
      name: "Turbo Carrot",
      icon: "🥕",
      price: 20,
      speed: 38,
      lift: 8,
      gravity: 18,
      boostDuration: 5,
      resistanceDuration: 8,
      description: "Boosts a horse and grants temporary interference resistance.",
    },
    hurdle: {
      name: "Foam Hurdle",
      icon: "🚧",
      price: 18,
      speed: 30,
      lift: 11,
      gravity: 17,
      slowDuration: 1.2,
      forceLaneChange: true,
      trap: true,
      heldScale: 0.58,
      description: "Stays on the track and forces the first horse it catches to change lanes.",
    },
    pillow: {
      name: "Throw Pillow",
      icon: "🛏️",
      price: 16,
      speed: 27,
      lift: 12,
      gravity: 13,
      ragdollDuration: 1.4,
      vendorOnly: true,
      description: "Concourse exclusive. Light, floaty, and startling.",
    },
    chair: {
      name: "Folding Chair",
      icon: "🪑",
      price: 42,
      speed: 25,
      lift: 9,
      gravity: 20,
      slowDuration: 4,
      ragdollDuration: 3.5,
      vendorOnly: true,
      description: "Concourse exclusive. Heavy, slow, and a powerful startle.",
    },
    pretzel: {
      name: "Giant Pretzel",
      icon: "🥨",
      price: 10,
      speed: 35,
      lift: 8,
      gravity: 18,
      slowDuration: 1.6,
      ragdollDuration: 1.1,
      heldScale: 0.78,
      description: "A bendy snack with a balanced arc and a short startle.",
    },
    performanceOats: {
      name: "Champion Oats",
      icon: "🌾",
      price: 24,
      speed: 32,
      lift: 9,
      gravity: 16,
      maxSpeedBonus: 0.01,
      maxSpeedBonusCap: 0.05,
      heldScale: 0.76,
      description: "Permanently raises a horse's maximum speed by 1%, stacking up to 5%.",
    },
    airHorn: {
      name: "Air Horn",
      icon: "\ud83d\udce3",
      price: 28,
      speed: 39,
      lift: 7,
      gravity: 19,
      panicDuration: 3.2,
      heldScale: 0.78,
      vendorOnly: true,
      description: "Concourse exclusive. Causes a panicked swerve and uneven pace.",
    },
  },
  sabotageOptions: {
    looseShoe: {
      name: "Sticky Starting Gate",
      price: 70,
      startDelay: 1.5,
      description: "Makes the target leave the gate 1.5 seconds late.",
    },
    badFeed: {
      name: "Missing Saddle Call",
      price: 105,
      startDelay: 2.8,
      description: "Delays the target at the start by 2.8 seconds.",
    },
    gateTampering: {
      name: "Weighted Saddle",
      price: 145,
      penalty: 0.15,
      description: "Reduces performance by 15% for the entire race.",
    },
    hotStart: {
      name: "Hot Start Tip",
      price: 90,
      boostDuration: 15,
      description: "Secretly boosts the target for the first 15 seconds.",
    },
  },
  sabotageFailureChance: 0.33,
  roundBonuses: [200, 300, 500],
  racesPerRound: 2,
  totalRaces: 6,
  raceLaps: 3,
  raceHorseCount: 6,
  horseFieldRaces: 2,
  trackLanes: {
    centerX: 53.35,
    centerZ: 25.68,
    spacingX: 2.85,
    spacingZ: 2.68,
    innerLineX: 51.925,
    innerLineZ: 24.34,
  },
  grandstandBaseHeight: 2.75,

  stairs: {
    startX: 78.5,
    startZ: 48,
    endX: 103.25,
    endZ: 69.75,
    width: 7.2,
    bottomHeight: 1.65,
    topHeight: 13.5,
  },
  liveBettingDuration: 15,
  preparationDuration: 45,
  roundBreakDuration: 60,
  phoneDeliveryDuration: 12,
  vendorDiscount: 0.33,
  onlineBetFeeRate: 0.08,
  throwVelocityMultiplier: 1,
  walkSpeed: 11.5,
  seat: new THREE.Vector3(8, 12.73, 60.85),
  playerSeatRoot: new THREE.Vector3(8, 9.45, 60.85),
  playerSeatYaw: 0,
  characterEyeOffset: 3.28,
  eyeHeight: 4.8,
};

HD.createInventory = () =>
  Object.fromEntries(Object.keys(HD.CONFIG.items).map((itemId) => [itemId, 0]));

HD.state = {
  money: 200,
  inventory: HD.createInventory(),
  selectedItem: "hotdog",
  round: 1,
  race: 1,
  selected: 0,
  bets: [],
  ledger: [],
  phase: "betting",
  timer: HD.CONFIG.preparationDuration,
  raceTime: 0,
  horses: [],
  activeHorseIds: [],
  horseFieldRacesRemaining: 0,
  horseBag: HD.CONFIG.horses.map((horse) => horse.id),
  horseSpeedBonuses: {},
  projectiles: [],
  finishOrder: [],
  elapsed: 0,
  lastOdds: 0,
  paused: true,
  mode: "look",
  yaw: 0,
  pitch: -0.18,
  throwPower: 0,
  charging: false,
  deliveries: [],
  standing: false,
  playerPosition: new THREE.Vector3(8, 12.73, 60.85),
  movement: { forward: false, backward: false, left: false, right: false },
  vendorOpen: false,
  counterOpen: false,
  sabotagePlans: [],
  raceAnnouncement: "",
  matchStarted: false,
  matchRules: {
    horseCount: 6,
    racesPerDay: 2,
    laps: 3,
    raceVariety: "standard",
    liveBetting: true,
  },
};
HD.world = {
  remotePlayers: new Map(),
};
HD.util = {
  material(color, extra = {}) {
    return new THREE.MeshStandardMaterial({ color, roughness: 0.78, metalness: 0.025, ...extra });
  },
  mesh(geometry, color, parent, position = [0, 0, 0], extra = {}) {
    const object = new THREE.Mesh(geometry, HD.util.material(color, extra));
    object.position.set(...position);
    object.castShadow = object.receiveShadow = true;
    parent.add(object);
    return object;
  },
  box(size, color, parent, position) {
    return HD.util.mesh(new THREE.BoxGeometry(...size), color, parent, position);
  },
  sphere(radius, color, parent, position) {
    return HD.util.mesh(new THREE.SphereGeometry(radius, 14, 10), color, parent, position);
  },
  cylinder(top, bottom, height, color, parent, position, segments = 12) {
    return HD.util.mesh(
      new THREE.CylinderGeometry(top, bottom, height, segments),
      color,
      parent,
      position,
    );
  },
};
